apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zav9xd6ox-java-springboot
  janus-idp.io/tekton: zav9xd6ox-java-springboot
  backstage.io/kubernetes-id: zav9xd6ox-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zav9xd6ox-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
